Add New Asset page
vegaprotocol/documentation pull request #166
Opened 2022-07-29 10:32 UTC by edd

Adds a tutorial poage for New Asset

2022-08-02 12:07 UTC, edd commented
Additional fields required:
```
✗ invalid request: proposal_submission.terms.change.new_asset.changes.source.erc20.lifetime_limit (is required), proposal_submission.terms.change.new_asset.changes.source.erc20.withdraw_threshold (is required)
```

2022-08-08 17:59 UTC, edd commented
This is kinda blocked by https://github.com/vegaprotocol/specs/issues/1178. However there is a missing field, `validationTimestamp`. which needs to be populated. It's a can of worms however...

2022-08-10 13:41 UTC, candida-d requested changes
This can't be merged until we can actually get a proposal working. I'm mainly reviewing this so I stop getting notified about it.

2022-08-25 15:30 UTC, candida-d approved these changes

2022-08-25 18:24 UTC, merged