Add page for websocket
vegaprotocol/documentation pull request #537
Opened 2023-03-16 13:20 UTC by candida-d

2023-03-23 11:56 UTC, wwestgarth commented
A few things to note:
- I removed `## Available websocket APIs` because 1) I didn't know how to do links!! and 2) they might all change anyway when we reshuffle the protos/move the subscription endpoints into their own section
- The new page doesn't appear in the sidebar anywhere, I wasn't sure where it should live
- We have a problem with the enums being ints instread of strings: I don't think there is anywhere in the autogenerate docs that would tell someone what each int means!

2023-03-23 12:08 UTC, edd approved these changes
I haven't run the code samples. Two validation things in JSON, one pedantic thing that @candida-d can agree/disagree with

2023-03-23 12:08 UTC, edd commented on docs/api/websocket.md
> +Websocket connections are ratelimited by a maximum allowed number of subscriptions per IP address. The default maximum is set to 250 connections but note that this value may differ between data node
```suggestion
Websocket connections are rate limited by a maximum allowed number of subscriptions per IP address. The default maximum is set to 250 connections but note that this value may differ between data node operators.
```

2023-03-23 12:08 UTC, edd commented on docs/api/websocket.md
> +            "orders": [],
```suggestion
            "orders": []
```

As above

2023-03-23 12:24 UTC, edd requested changes
JS is broken. I'll fix it.

2023-03-23 12:24 UTC, edd commented on docs/api/websocket.md
> +url = "wss://api.n07.testnet.vega.xyz/api/v2/stream/ledger/movements"
```suggestion
var url = "wss://api.n07.testnet.vega.xyz/api/v2/stream/ledger/movements"
```

2023-03-28 09:06 UTC, edd approved these changes

2023-04-03 16:18 UTC, merged