Extended LP fee options
vegaprotocol/documentation pull request #822
Opened 2023-11-10 17:29 UTC by candida-d

2024-01-26 15:22 UTC, candida-d commented on docs/tutorials/proposals/new-market-proposal.md
> +| `liquidityFeeSettings` | Optional setting for how the liquidity fee factor is determined. See [liquidity fees](../../concepts/liquidity/rewards-penalties.md#determining-the-liquidity-fee-percentage
Add detail about `feeConstant` sub-field if constant is chosen as a "string"

2024-01-30 11:23 UTC, davidsiska-vega commented on docs/concepts/liquidity/rewards-penalties.md
> +The market's liquidity fee is provided in the market proposal and this percentage doesn't vary. The fee percentage can be changed in an update market proposal.
And the method can be changed in an update market proposal - I am not sure that needs to be stressed.

2024-01-30 11:24 UTC, davidsiska-vega commented on docs/concepts/liquidity/rewards-penalties.md
> +Each liquidity provider submits their desired liquidity fee factor in the liquidity commitment transaction. It’s a number between 0 and 1. Each fee factor has a weight assigned to it based on the sup
@Jiajia-Cui I thought it's the weighted average, not the LP with the highest weight. Is that correct?

2024-01-30 11:24 UTC, davidsiska-vega requested changes
Left a comment and a question for Jiajia.

2024-01-31 15:48 UTC, davidsiska-vega approved these changes

2024-01-31 15:51 UTC, merged