Network treasury & governance folder
vegaprotocol/documentation pull request #953
Opened 2024-02-23 18:40 UTC by candida-d

Closes #890. Also breaks out existing governance content into multiple pages.

2024-03-06 17:02 UTC, candida-d commented on docs/concepts/governance/treasury.md
> +-->
```suggestion
```

2024-03-07 13:03 UTC, barnabee requested changes
Made some suggestions, also ran out of time adding links 'cos I have another call so there are a few "needs a link" type notes in there, sorry!

2024-03-13 15:26 UTC, edd commented on docs/concepts/governance/treasury.md
> +* To vote a proposal, you usually need at least 1 VEGA, but the amount may vary per proposal type. Check the [block explorer](https://explorer.fairground.wtf/network-parameters) for each `minVoterBal
```suggestion
* To vote on a proposal, you usually need at least 1 VEGA, but the amount may vary per proposal type. Check the [block explorer](https://explorer.fairground.wtf/network-parameters) for each `minVoterBalance`.
```

2024-03-13 15:26 UTC, edd commented on docs/concepts/governance/treasury.md
> +Assets can only be spend from the on-chain treasury by governance, when a **[proposal to transfer assets](../assets/transfers.md#governance-initiated-transfers)** is enacted.
```suggestion
Assets can only be spent from the on-chain treasury by governance, when a **[proposal to transfer assets](../assets/transfers.md#governance-initiated-transfers)** is enacted. 
```

2024-03-13 15:26 UTC, edd commented on docs/concepts/governance/treasury.md
> +The most direct way to propose spending the assets is by submitting one of these proposals. In practice, community members almost always discuss proposals on the **[Vega community forums ↗](https://c
```suggestion
The most direct way to propose spending the assets is by submitting one of these proposals. In practice, community members almost always discuss proposals on the  **[Vega community forums ↗](https://community.vega.xyz/) before submitting**, in order to incorporate community feedback into the proposal and ensure there's broad support before going through the effort of putting it on-chain.
```

2024-03-13 15:26 UTC, edd commented on versioned_docs/version-v0.74/concepts/governance/treasury.md
> +Assets can only be spend from the on-chain treasury by governance, when a [proposal to transfer assets](../assets/transfers.md#governance-initiated-transfers) is enacted.
```suggestion
Assets can only be spent from the on-chain treasury by governance, when a [proposal to transfer assets](../assets/transfers.md#governance-initiated-transfers) is enacted. 
```

2024-03-13 15:26 UTC, edd commented on versioned_docs/version-v0.74/concepts/governance/treasury.md
> +* To vote a proposal, you need at least 1 VEGA, but the minimum amount can vary per proposal type. Check the [block explorer ↗](https://explorer.fairground.wtf/network-parameters) for each `minVoterB
```suggestion
* To vote on a proposal, you need at least 1 VEGA, but the minimum amount can vary per proposal type. Check the [block explorer ↗](https://explorer.fairground.wtf/network-parameters) for each `minVoterBalance`.
```

2024-03-13 15:26 UTC, edd commented on versioned_docs/version-v0.74/concepts/governance/treasury.md
> +The most direct way to propose spending the assets is by submitting one of these proposals. In practice, community members almost always **discuss proposals on the[Vega community forums ↗](https://co
```suggestion
The most direct way to propose spending the assets is by submitting one of these proposals. In practice, community members almost always **discuss proposals on the [Vega community forums ↗](https://community.vega.xyz/) before submitting**, in order to incorporate community feedback into the proposal and ensure there's broad support before going through the effort of putting it on-chain.
```

2024-03-13 16:27 UTC, merged